spring:
  application:
    name: SBB
  profiles:
    active: prod
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user-name-attribute: response
  mail:
    host: smtp.naver.com
    port: 587
    username: ${NAVER_EMAIL_USERNAME}
    password: ${NAVER_EMAIL_PASSWORD}
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${SBB_REDIS_HOST}
      port: ${SBB_REDIS_PORT}
      password: ${SBB_REDIS_PASSWORD}

server:
  port: 8080